volumes:
    pg_volume:                                
        name: pg_volume
    rabbitmq_volume:
        name: rabbitmq_volume

services: 
    postgres:
        image: postgres
        ports:
          - 5432:5432
        volumes:
          - pg_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${PG_NAME}
            POSTGRES_USER: ${PG_USERNAME}
            POSTGRES_PASSWORD: ${PG_PASSWORD}

    mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025
    
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
          - 5672:5672
          - 15672:15672
        volumes:
          - rabbitmq_volume:/var/lib/rabbitmq/data
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}